"""melhorando o relationship entre pedido e cliente

Revision ID: 809e14226020
Revises: 4098830ef6e7
Create Date: 2026-08-26 12:35:10.378230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '809e14226020'
down_revision = '4098830ef6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
