"""melhorando o relationship entre pedido e cliente

Revision ID: 809e14226020
Revises: 4098830ef6e7
Create Date: 2026-08-26 12:35:10.378230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '809e14226020'
down_revision = '4098830ef6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('pedido')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_cliente_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_cliente_id'), ['cliente_id'], unique=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
