"""estrutura inicial

Revision ID: caffd29e0299
Revises: 
Create Date: 2026-08-26 12:01:51.196235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caffd29e0299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('pedido', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('codigo_recuperacao', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('data_pedido', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('relatorio',
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], )
    )
    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relatorio_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_relatorio_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relatorio_produto_id'), ['produto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relatorio_produto_id'))
        batch_op.drop_index(batch_op.f('ix_relatorio_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_relatorio_id_cliente'))

    op.drop_table('relatorio')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_cliente_id'))

    op.drop_table('pedido')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
