"""ajustando a tabela pedido

Revision ID: e1a09b99cb0e
Revises: 809e14226020
Create Date: 2026-08-29 23:17:42.218813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1a09b99cb0e'
down_revision = '809e14226020'
branch_labels = None
depends_on = None

def upgrade():

    op.drop_table('relatorio')

    with op.batch_alter_table('pedido', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column('produto_id', sa.Integer(), nullable=True)
        )

        batch_op.add_column(
            sa.Column('quantidade', sa.Integer(), nullable=True)
        )

        batch_op.create_index(
            batch_op.f('ix_pedido_produto_id'),
            ['produto_id'],
            unique=False
        )

        batch_op.create_foreign_key(
            None,
            'produto',
            ['produto_id'],
            ['id']
        )

        batch_op.drop_column('status')

    with op.batch_alter_table('usuario', schema=None) as batch_op:

        batch_op.drop_column('codigo_recuperacao')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_recuperacao', mysql.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pedido_produto_id'))
        batch_op.drop_column('quantidade')
        batch_op.drop_column('produto_id')

    op.create_table('relatorio',
    sa.Column('id_cliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pedido_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('produto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], name=op.f('relatorio_ibfk_1')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('relatorio_ibfk_2')),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name=op.f('relatorio_ibfk_3')),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relatorio_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relatorio_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relatorio_id_cliente'), ['id_cliente'], unique=False)

    with op.batch_alter_table('itens_pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedidos_produto_id'))
        batch_op.drop_index(batch_op.f('ix_itens_pedidos_pedido_id'))

    op.drop_table('itens_pedidos')
    # ### end Alembic commands ###
